print("The Love Calculator is calculating your score...")
name1 = input("What is your name?") 
name2 = input("What is their name?")
name_11=name1.lower()
name_22=name2.lower()
t_1=name_11.count('t')
t_2=name_22.count('t')
r_1=name_11.count('r')
r_2=name_22.count('r')
u_1=name_11.count('u')
u_2=name_22.count('u')
e_1=name_11.count('e')
e_2=name_22.count('e')
t=int(t_1+t_2+r_1+r_2+u_1+u_2+e_1+e_2)
l_1=name_11.count('l')
l_2=name_22.count('l')
o_1=name_11.count('o')
o_2=name_22.count('o')
v_1=name_11.count('v')
v_2=name_22.count('v')
e_1=name_11.count('e')
e_2=name_22.count('e')
l=int(l_1+l_2+o_1+o_2+v_1+v_2+e_1+e_2)
true=str(t)
love=str(l)
score=true+love
total=int(score)
if (total<10 or total >90):
  print (f"Your score is {total}, you go together like coke and mentos.")
elif (total>40 and total <50):
  print (f"Your score is {total}, you are alright together.")
else:
  print(f"Your score is {total}.")
